### ISSUE TITLE
Bug With Slurping Body With Python multipart/related Content-Type

### ISSUE THREAD

**Issue by turnkey-commerce** [mailslurper/libmailslurper#9]
When sending mail from Python with multipart/related Content-Type, the body will fail to be slurped due to an issue with the way the content is rendered from Python (using standard libraries).  Below is the error message encountered and attached is a Python file to reproduce the issue.

**Reproducing Python Script:**
[python_mail.zip](https://github.com/mailslurper/libmailslurper/files/139230/python_mail.zip)

**Error Log:**
```
2016/02/20 10:17:11 libmailslurper: INFO - Mail Date:  Sat, 20 Feb 2016 10:17:10 -0600
2016/02/20 10:17:11 libmailslurper: ERROR - Expected attachment to contain a header section and a body section
2016/02/20 10:17:11 libmailslurper: INFO - Attachment Content-Type:  multipart/alternative; boundary="===============1475100378=="
2016/02/20 10:17:11 libmailslurper: INFO - Attachment MIME-Version:  1.0
2016/02/20 10:17:11 libmailslurper: INFO - Closing connection
```

**Comment by adampresley** [comment]
Moved this over to the main project. Issue #34
